- name: Bootstrap
  hosts: all
  become: true
  vars:
    fluentbit_additional_inputs:
      - Name: Tail
        Path: /var/log/elasticsearch/elasticsearch.log
        Path_key: file_name
        Tag: system.file.elasticsearch
        # Parser: syslog-rfc3164-local-custom TODO: this
        Mem_Buf_Limit: 5MB
        Skip_Long_Lines: "On"
        DB: /var/lib/fluent-bit/tail-elasticsearch-state.db
        DB.Sync: Normal
      - Name: Tail
        Path: /var/log/elasticsearch/elasticsearch_audit.json
        Path_key: file_name
        Tag: system.file.elasticsearch_audit
        Parser: json
        Mem_Buf_Limit: 5MB
        Skip_Long_Lines: "On"
        DB: /var/lib/fluent-bit/tail-elasticsearch-audit-state.db
        DB.Sync: Normal
      - Name: Tail
        Path: /var/log/elasticsearch/elasticsearch_deprecation.json
        Path_key: file_name
        Tag: system.file.elasticsearch_deprecation
        Parser: json
        Mem_Buf_Limit: 5MB
        Skip_Long_Lines: "On"
        DB: /var/lib/fluent-bit/tail-elasticsearch-deprecation-state.db
        DB.Sync: Normal
      - Name: Tail
        Path: /var/log/elasticsearch/elasticsearch_index_indexing_slowlog.json
        Path_key: file_name
        Tag: system.file.elasticsearch_index_indexing_slowlog
        Parser: json
        Mem_Buf_Limit: 5MB
        Skip_Long_Lines: "On"
        DB: /var/lib/fluent-bit/tail-elasticsearch-indexing-slowlog-state.db
        DB.Sync: Normal
      - Name: Tail
        Path: /var/log/elasticsearch/elasticsearch_index_search_slowlog.json
        Path_key: file_name
        Tag: system.file.elasticsearch_index_search_slowlog
        Parser: json
        Mem_Buf_Limit: 5MB
        Skip_Long_Lines: "On"
        DB: /var/lib/fluent-bit/tail-elasticsearch-search-slowlog-state.db
        DB.Sync: Normal
      - Name: Tail
        Path: /var/log/elasticsearch/elasticsearch_server.json
        Path_key: file_name
        Tag: system.file.elasticsearch_server
        Parser: json
        Mem_Buf_Limit: 5MB
        Skip_Long_Lines: "On"
        DB: /var/lib/fluent-bit/tail-elasticsearch-server-state.db
        DB.Sync: Normal
  roles:
    - rmb938.bootstrap

- name: Elasticsearch
  hosts: all
  become: true
  roles:
    - elasticsearch
    - kibana
