---
- name: Install Kibana
  ansible.builtin.package:
    name: kibana
    state: present

- name: Configure Kibana Node Options
  ansible.builtin.template:
    src: etc/kibana/node.options
    dest: /etc/kibana/node.options
    mode: "0664"
  register: kibana_node_options_config

- name: Check if Kibana Service Account Exists
  ansible.builtin.stat:
    path: /etc/kibana/service_account_token
  register: kibana_service_account_token_file

- name: Create Kibana Service Account
  when: not kibana_service_account_token_file.stat.exists
  block:
    - name: Create Kibana SA Token
      ansible.builtin.command:
        cmd: "/usr/share/elasticsearch/bin/elasticsearch-service-tokens create elastic/kibana ansible"
      register: kibana_service_account_token_create
      changed_when: false

    - name: Save Service Account to File
      ansible.builtin.copy:
        dest: /etc/kibana/service_account_token
        content: "{{ kibana_service_account_token_create.stdout.split('=')[1] | trim }}"
        owner: root
        group: kibana
        mode: "0640"

- name: Read Kibana Service Account
  ansible.builtin.slurp:
    src: /etc/kibana/service_account_token
  register: kibana_service_account_token

- name: Make Kibana certs dir
  ansible.builtin.file:
    path: /etc/kibana/certs
    owner: root
    group: kibana
    mode: "0770"
    state: directory

- name: Create Kibana Certificates
  ansible.builtin.command: >-
    step ca certificate {{ ansible_fqdn }}
    /etc/kibana/certs/kibana-http.crt
    /etc/kibana/certs/kibana-http.crt.key
    --ca-url https://step-ca.us-homelab1.hl.rmb938.me:8443
    --root /usr/local/share/ca-certificates/smallstep-homelab-prod.crt
  args:
    creates: "/etc/kibana/certs/kibana-http.crt"

- name: Own Kibana certificates
  ansible.builtin.file:
    path: /etc/kibana/certs/{{ item }}
    owner: kibana
    group: kibana
    mode: "0600"
  with_items:
    - kibana-http.crt
    - kibana-http.crt.key

- name: Cron to renew Kibana certificates
  ansible.builtin.cron:
    name: "renew Kibana certificates"
    special_time: "hourly"
    # Rekey needs to happen against the CA, RA's don't support rekey
    # https://smallstep.com/docs/step-ca/registration-authority-ra-mode/#stepcas-limitations
    # We don't need to reload/restart Kibana as it will reload the certs on it's own
    job: >-
      step ca rekey /etc/kibana/certs/kibana-http.crt
      /etc/kibana/certs/kibana-http.crt.key
      --ca-url https://step-ca.us-homelab1.hl.rmb938.me
      --root /usr/local/share/ca-certificates/smallstep-homelab-prod.crt
      --force --expires-in 720h
    state: present

- name: Configure Kibana
  ansible.builtin.template:
    src: etc/kibana/kibana.yml
    dest: /etc/kibana/kibana.yml
    mode: "0660"
  register: kibana_config

- name: Start Kibana
  ansible.builtin.systemd:
    service: kibana
    state: started
    enabled: true

- name: Restart kibana if config changed # noqa: no-handler
  ansible.builtin.systemd:
    name: kibana
    state: restarted
  when: kibana_node_options_config.changed or kibana_config.changed

# TODO: enroll kibana /usr/share/kibana/bin/kibana-setup -t <token>
